/********************************************************************************
** Form generated from reading UI file 'tspresult.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TSPRESULT_H
#define UI_TSPRESULT_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_TSPResult
{
public:
    QPushButton *buttStartPath;
    QPushButton *buttDoubleReplacement;
    QPushButton *buttTripleReplacement;
    QPushButton *buttFourthReplacement;
    QLabel *labelTime;
    QLabel *labelResult;
    QLabel *labelTimeStart;
    QLabel *labelTime2;
    QLabel *labelTime3;
    QLabel *labelTime4;
    QLabel *labelResultStart;
    QLabel *labelResult2;
    QLabel *labelResult3;
    QLabel *labelResult4;
    QLabel *labelPath;
    QLabel *labelPathStart;
    QLabel *labelPath2;
    QLabel *labelPath3;
    QLabel *labelPath4;
    QLabel *labelStartPoint;
    QLineEdit *editStartPoint;
    QPushButton *buttAllAlgorythm;
    QProgressBar *progressStartPathAccuracy;
    QProgressBar *progressDoubleReplaceAccuracy;
    QProgressBar *progressTrippleReplaceAccuracy;
    QProgressBar *progressQuadroReplaceAccuracy;
    QProgressBar *progressStartPathTime;
    QProgressBar *progressTrippleReplaceTime;
    QProgressBar *progressQuadroReplaceTime;
    QProgressBar *progressDoubleReplaceTIme;
    QLabel *label_Time;
    QLabel *label_accuracy;
    QPushButton *buttRandomGenerate;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *editPointFrom;
    QLineEdit *editPointTo;
    QLineEdit *editPointStep;
    QLabel *label_5;
    QLabel *label_6;
    QLineEdit *editLengthTo;
    QLabel *label_7;
    QLineEdit *editLengthFrom;
    QLabel *label_8;
    QLineEdit *editQuantCycle;
    QLabel *label_9;
    QLabel *label_10;

    void setupUi(QWidget *TSPResult)
    {
        if (TSPResult->objectName().isEmpty())
            TSPResult->setObjectName(QStringLiteral("TSPResult"));
        TSPResult->resize(1009, 593);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        TSPResult->setPalette(palette);
        buttStartPath = new QPushButton(TSPResult);
        buttStartPath->setObjectName(QStringLiteral("buttStartPath"));
        buttStartPath->setEnabled(true);
        buttStartPath->setGeometry(QRect(20, 80, 151, 31));
        QPalette palette1;
        QBrush brush2(QColor(0, 255, 212, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        QBrush brush3(QColor(190, 190, 190, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        buttStartPath->setPalette(palette1);
        QFont font;
        font.setPointSize(14);
        buttStartPath->setFont(font);
        buttDoubleReplacement = new QPushButton(TSPResult);
        buttDoubleReplacement->setObjectName(QStringLiteral("buttDoubleReplacement"));
        buttDoubleReplacement->setGeometry(QRect(20, 130, 151, 41));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        buttDoubleReplacement->setPalette(palette2);
        buttDoubleReplacement->setFont(font);
        buttTripleReplacement = new QPushButton(TSPResult);
        buttTripleReplacement->setObjectName(QStringLiteral("buttTripleReplacement"));
        buttTripleReplacement->setGeometry(QRect(20, 190, 151, 41));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        buttTripleReplacement->setPalette(palette3);
        buttTripleReplacement->setFont(font);
        buttFourthReplacement = new QPushButton(TSPResult);
        buttFourthReplacement->setObjectName(QStringLiteral("buttFourthReplacement"));
        buttFourthReplacement->setGeometry(QRect(20, 250, 151, 41));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        buttFourthReplacement->setPalette(palette4);
        buttFourthReplacement->setFont(font);
        labelTime = new QLabel(TSPResult);
        labelTime->setObjectName(QStringLiteral("labelTime"));
        labelTime->setGeometry(QRect(210, 30, 111, 17));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelTime->setPalette(palette5);
        labelTime->setFont(font);
        labelResult = new QLabel(TSPResult);
        labelResult->setObjectName(QStringLiteral("labelResult"));
        labelResult->setGeometry(QRect(320, 30, 101, 17));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelResult->setPalette(palette6);
        labelResult->setFont(font);
        labelTimeStart = new QLabel(TSPResult);
        labelTimeStart->setObjectName(QStringLiteral("labelTimeStart"));
        labelTimeStart->setGeometry(QRect(200, 90, 101, 17));
        QPalette palette7;
        QBrush brush4(QColor(255, 0, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelTimeStart->setPalette(palette7);
        labelTimeStart->setFont(font);
        labelTime2 = new QLabel(TSPResult);
        labelTime2->setObjectName(QStringLiteral("labelTime2"));
        labelTime2->setGeometry(QRect(200, 150, 101, 17));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelTime2->setPalette(palette8);
        labelTime2->setFont(font);
        labelTime3 = new QLabel(TSPResult);
        labelTime3->setObjectName(QStringLiteral("labelTime3"));
        labelTime3->setGeometry(QRect(200, 200, 101, 17));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelTime3->setPalette(palette9);
        labelTime3->setFont(font);
        labelTime4 = new QLabel(TSPResult);
        labelTime4->setObjectName(QStringLiteral("labelTime4"));
        labelTime4->setGeometry(QRect(200, 260, 101, 17));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelTime4->setPalette(palette10);
        labelTime4->setFont(font);
        labelResultStart = new QLabel(TSPResult);
        labelResultStart->setObjectName(QStringLiteral("labelResultStart"));
        labelResultStart->setGeometry(QRect(320, 90, 101, 17));
        QPalette palette11;
        QBrush brush5(QColor(0, 249, 38, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelResultStart->setPalette(palette11);
        labelResultStart->setFont(font);
        labelResult2 = new QLabel(TSPResult);
        labelResult2->setObjectName(QStringLiteral("labelResult2"));
        labelResult2->setGeometry(QRect(320, 150, 91, 17));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelResult2->setPalette(palette12);
        labelResult2->setFont(font);
        labelResult3 = new QLabel(TSPResult);
        labelResult3->setObjectName(QStringLiteral("labelResult3"));
        labelResult3->setGeometry(QRect(320, 200, 101, 17));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelResult3->setPalette(palette13);
        labelResult3->setFont(font);
        labelResult4 = new QLabel(TSPResult);
        labelResult4->setObjectName(QStringLiteral("labelResult4"));
        labelResult4->setGeometry(QRect(320, 260, 101, 17));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelResult4->setPalette(palette14);
        labelResult4->setFont(font);
        labelPath = new QLabel(TSPResult);
        labelPath->setObjectName(QStringLiteral("labelPath"));
        labelPath->setGeometry(QRect(760, 30, 67, 17));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelPath->setPalette(palette15);
        labelPath->setFont(font);
        labelPathStart = new QLabel(TSPResult);
        labelPathStart->setObjectName(QStringLiteral("labelPathStart"));
        labelPathStart->setGeometry(QRect(740, 90, 821, 17));
        QPalette palette16;
        QBrush brush6(QColor(237, 212, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelPathStart->setPalette(palette16);
        labelPathStart->setFont(font);
        labelPath2 = new QLabel(TSPResult);
        labelPath2->setObjectName(QStringLiteral("labelPath2"));
        labelPath2->setGeometry(QRect(740, 150, 831, 17));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelPath2->setPalette(palette17);
        labelPath2->setFont(font);
        labelPath3 = new QLabel(TSPResult);
        labelPath3->setObjectName(QStringLiteral("labelPath3"));
        labelPath3->setGeometry(QRect(740, 200, 841, 17));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelPath3->setPalette(palette18);
        labelPath3->setFont(font);
        labelPath4 = new QLabel(TSPResult);
        labelPath4->setObjectName(QStringLiteral("labelPath4"));
        labelPath4->setGeometry(QRect(740, 260, 841, 17));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelPath4->setPalette(palette19);
        labelPath4->setFont(font);
        labelStartPoint = new QLabel(TSPResult);
        labelStartPoint->setObjectName(QStringLiteral("labelStartPoint"));
        labelStartPoint->setGeometry(QRect(280, 310, 431, 17));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        labelStartPoint->setPalette(palette20);
        labelStartPoint->setFont(font);
        editStartPoint = new QLineEdit(TSPResult);
        editStartPoint->setObjectName(QStringLiteral("editStartPoint"));
        editStartPoint->setGeometry(QRect(280, 340, 113, 25));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush7(QColor(238, 238, 236, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        editStartPoint->setPalette(palette21);
        QFont font1;
        font1.setPointSize(13);
        editStartPoint->setFont(font1);
        buttAllAlgorythm = new QPushButton(TSPResult);
        buttAllAlgorythm->setObjectName(QStringLiteral("buttAllAlgorythm"));
        buttAllAlgorythm->setGeometry(QRect(20, 320, 171, 51));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        buttAllAlgorythm->setPalette(palette22);
        buttAllAlgorythm->setFont(font);
        progressStartPathAccuracy = new QProgressBar(TSPResult);
        progressStartPathAccuracy->setObjectName(QStringLiteral("progressStartPathAccuracy"));
        progressStartPathAccuracy->setGeometry(QRect(460, 90, 118, 23));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush8(QColor(115, 210, 22, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette23.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette23.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        QBrush brush9(QColor(145, 145, 145, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette23.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressStartPathAccuracy->setPalette(palette23);
        progressStartPathAccuracy->setFont(font1);
        progressStartPathAccuracy->setValue(0);
        progressDoubleReplaceAccuracy = new QProgressBar(TSPResult);
        progressDoubleReplaceAccuracy->setObjectName(QStringLiteral("progressDoubleReplaceAccuracy"));
        progressDoubleReplaceAccuracy->setGeometry(QRect(460, 150, 118, 23));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette24.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette24.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressDoubleReplaceAccuracy->setPalette(palette24);
        progressDoubleReplaceAccuracy->setFont(font1);
        progressDoubleReplaceAccuracy->setValue(0);
        progressTrippleReplaceAccuracy = new QProgressBar(TSPResult);
        progressTrippleReplaceAccuracy->setObjectName(QStringLiteral("progressTrippleReplaceAccuracy"));
        progressTrippleReplaceAccuracy->setGeometry(QRect(460, 200, 118, 23));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette25.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressTrippleReplaceAccuracy->setPalette(palette25);
        progressTrippleReplaceAccuracy->setFont(font1);
        progressTrippleReplaceAccuracy->setValue(0);
        progressQuadroReplaceAccuracy = new QProgressBar(TSPResult);
        progressQuadroReplaceAccuracy->setObjectName(QStringLiteral("progressQuadroReplaceAccuracy"));
        progressQuadroReplaceAccuracy->setGeometry(QRect(460, 260, 118, 23));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette26.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette26.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressQuadroReplaceAccuracy->setPalette(palette26);
        progressQuadroReplaceAccuracy->setFont(font1);
        progressQuadroReplaceAccuracy->setValue(0);
        progressStartPathTime = new QProgressBar(TSPResult);
        progressStartPathTime->setObjectName(QStringLiteral("progressStartPathTime"));
        progressStartPathTime->setGeometry(QRect(610, 90, 118, 23));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush10(QColor(204, 0, 0, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette27.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette27.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressStartPathTime->setPalette(palette27);
        progressStartPathTime->setFont(font1);
        progressStartPathTime->setAutoFillBackground(false);
        progressStartPathTime->setValue(0);
        progressTrippleReplaceTime = new QProgressBar(TSPResult);
        progressTrippleReplaceTime->setObjectName(QStringLiteral("progressTrippleReplaceTime"));
        progressTrippleReplaceTime->setGeometry(QRect(610, 200, 118, 23));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette28.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette28.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressTrippleReplaceTime->setPalette(palette28);
        progressTrippleReplaceTime->setFont(font1);
        progressTrippleReplaceTime->setAutoFillBackground(false);
        progressTrippleReplaceTime->setValue(0);
        progressQuadroReplaceTime = new QProgressBar(TSPResult);
        progressQuadroReplaceTime->setObjectName(QStringLiteral("progressQuadroReplaceTime"));
        progressQuadroReplaceTime->setGeometry(QRect(610, 260, 118, 23));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette29.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette29.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressQuadroReplaceTime->setPalette(palette29);
        progressQuadroReplaceTime->setFont(font1);
        progressQuadroReplaceTime->setAutoFillBackground(false);
        progressQuadroReplaceTime->setValue(0);
        progressDoubleReplaceTIme = new QProgressBar(TSPResult);
        progressDoubleReplaceTIme->setObjectName(QStringLiteral("progressDoubleReplaceTIme"));
        progressDoubleReplaceTIme->setGeometry(QRect(610, 150, 118, 23));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette30.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette30.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette30.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        progressDoubleReplaceTIme->setPalette(palette30);
        progressDoubleReplaceTIme->setFont(font1);
        progressDoubleReplaceTIme->setAutoFillBackground(false);
        progressDoubleReplaceTIme->setValue(0);
        label_Time = new QLabel(TSPResult);
        label_Time->setObjectName(QStringLiteral("label_Time"));
        label_Time->setGeometry(QRect(630, 30, 67, 17));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_Time->setPalette(palette31);
        label_Time->setFont(font);
        label_accuracy = new QLabel(TSPResult);
        label_accuracy->setObjectName(QStringLiteral("label_accuracy"));
        label_accuracy->setGeometry(QRect(470, 20, 111, 31));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_accuracy->setPalette(palette32);
        label_accuracy->setFont(font);
        buttRandomGenerate = new QPushButton(TSPResult);
        buttRandomGenerate->setObjectName(QStringLiteral("buttRandomGenerate"));
        buttRandomGenerate->setEnabled(false);
        buttRandomGenerate->setGeometry(QRect(560, 530, 291, 51));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        buttRandomGenerate->setPalette(palette33);
        buttRandomGenerate->setFont(font);
        radioButton = new QRadioButton(TSPResult);
        radioButton->setObjectName(QStringLiteral("radioButton"));
        radioButton->setGeometry(QRect(30, 410, 181, 23));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        radioButton->setPalette(palette34);
        radioButton->setFont(font);
        radioButton->setChecked(true);
        radioButton_2 = new QRadioButton(TSPResult);
        radioButton_2->setObjectName(QStringLiteral("radioButton_2"));
        radioButton_2->setGeometry(QRect(30, 450, 281, 23));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        radioButton_2->setPalette(palette35);
        radioButton_2->setFont(font);
        label = new QLabel(TSPResult);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(650, 330, 141, 31));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label->setPalette(palette36);
        label->setFont(font);
        label_2 = new QLabel(TSPResult);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(430, 370, 51, 17));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_2->setPalette(palette37);
        label_2->setFont(font);
        label_3 = new QLabel(TSPResult);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(610, 370, 31, 17));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_3->setPalette(palette38);
        label_3->setFont(font);
        label_4 = new QLabel(TSPResult);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(780, 350, 41, 51));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_4->setPalette(palette39);
        label_4->setFont(font);
        editPointFrom = new QLineEdit(TSPResult);
        editPointFrom->setObjectName(QStringLiteral("editPointFrom"));
        editPointFrom->setEnabled(false);
        editPointFrom->setGeometry(QRect(490, 370, 113, 25));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::Base, brush);
        palette40.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette40.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette40.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette40.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette40.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette40.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette40.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette40.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        editPointFrom->setPalette(palette40);
        editPointFrom->setFont(font1);
        editPointTo = new QLineEdit(TSPResult);
        editPointTo->setObjectName(QStringLiteral("editPointTo"));
        editPointTo->setEnabled(false);
        editPointTo->setGeometry(QRect(650, 370, 113, 25));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::Base, brush);
        palette41.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette41.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette41.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette41.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette41.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette41.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette41.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette41.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        editPointTo->setPalette(palette41);
        editPointTo->setFont(font1);
        editPointStep = new QLineEdit(TSPResult);
        editPointStep->setObjectName(QStringLiteral("editPointStep"));
        editPointStep->setEnabled(false);
        editPointStep->setGeometry(QRect(830, 370, 113, 25));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::Base, brush);
        palette42.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette42.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette42.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette42.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette42.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette42.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette42.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette42.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        editPointStep->setPalette(palette42);
        editPointStep->setFont(font1);
        label_5 = new QLabel(TSPResult);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(640, 420, 141, 17));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette43.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_5->setPalette(palette43);
        label_5->setFont(font);
        label_6 = new QLabel(TSPResult);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(480, 450, 61, 17));
        QPalette palette44;
        palette44.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette44.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_6->setPalette(palette44);
        label_6->setFont(font);
        editLengthTo = new QLineEdit(TSPResult);
        editLengthTo->setObjectName(QStringLiteral("editLengthTo"));
        editLengthTo->setEnabled(false);
        editLengthTo->setGeometry(QRect(760, 450, 113, 25));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::Base, brush);
        palette45.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette45.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette45.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette45.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette45.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette45.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette45.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette45.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        editLengthTo->setPalette(palette45);
        editLengthTo->setFont(font1);
        label_7 = new QLabel(TSPResult);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setEnabled(true);
        label_7->setGeometry(QRect(700, 450, 31, 17));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette46.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette46.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_7->setPalette(palette46);
        label_7->setFont(font);
        editLengthFrom = new QLineEdit(TSPResult);
        editLengthFrom->setObjectName(QStringLiteral("editLengthFrom"));
        editLengthFrom->setEnabled(false);
        editLengthFrom->setGeometry(QRect(540, 450, 113, 25));
        QPalette palette47;
        palette47.setBrush(QPalette::Active, QPalette::Base, brush);
        palette47.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette47.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette47.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette47.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette47.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette47.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette47.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette47.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        editLengthFrom->setPalette(palette47);
        editLengthFrom->setFont(font1);
        label_8 = new QLabel(TSPResult);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(490, 490, 141, 31));
        QPalette palette48;
        palette48.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette48.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette48.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_8->setPalette(palette48);
        label_8->setFont(font);
        editQuantCycle = new QLineEdit(TSPResult);
        editQuantCycle->setObjectName(QStringLiteral("editQuantCycle"));
        editQuantCycle->setEnabled(false);
        editQuantCycle->setGeometry(QRect(640, 490, 141, 31));
        QPalette palette49;
        palette49.setBrush(QPalette::Active, QPalette::Base, brush);
        palette49.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette49.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette49.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette49.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette49.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette49.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette49.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette49.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        editQuantCycle->setPalette(palette49);
        editQuantCycle->setFont(font1);
        label_9 = new QLabel(TSPResult);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(30, 520, 191, 31));
        QPalette palette50;
        palette50.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette50.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette50.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_9->setPalette(palette50);
        label_9->setFont(font);
        label_10 = new QLabel(TSPResult);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(220, 520, 191, 31));
        QPalette palette51;
        palette51.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette51.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette51.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        label_10->setPalette(palette51);
        QFont font2;
        font2.setPointSize(16);
        label_10->setFont(font2);

        retranslateUi(TSPResult);

        QMetaObject::connectSlotsByName(TSPResult);
    } // setupUi

    void retranslateUi(QWidget *TSPResult)
    {
        TSPResult->setWindowTitle(QApplication::translate("TSPResult", "Form", nullptr));
        buttStartPath->setText(QApplication::translate("TSPResult", "Start path", nullptr));
        buttDoubleReplacement->setText(QApplication::translate("TSPResult", "2 replacement", nullptr));
        buttTripleReplacement->setText(QApplication::translate("TSPResult", "3 replacement", nullptr));
        buttFourthReplacement->setText(QApplication::translate("TSPResult", "4 replacement", nullptr));
        labelTime->setText(QApplication::translate("TSPResult", "Time (nsec)", nullptr));
        labelResult->setText(QApplication::translate("TSPResult", "Path length", nullptr));
        labelTimeStart->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelTime2->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelTime3->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelTime4->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelResultStart->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelResult2->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelResult3->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelResult4->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelPath->setText(QApplication::translate("TSPResult", "Path", nullptr));
        labelPathStart->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelPath2->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelPath3->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelPath4->setText(QApplication::translate("TSPResult", "TextLabel", nullptr));
        labelStartPoint->setText(QApplication::translate("TSPResult", "Start Point", nullptr));
        editStartPoint->setText(QApplication::translate("TSPResult", "1", nullptr));
        buttAllAlgorythm->setText(QApplication::translate("TSPResult", "Find All Value", nullptr));
        label_Time->setText(QApplication::translate("TSPResult", "Time", nullptr));
        label_accuracy->setText(QApplication::translate("TSPResult", "Efficiency", nullptr));
        buttRandomGenerate->setText(QApplication::translate("TSPResult", "Configure random generate", nullptr));
        radioButton->setText(QApplication::translate("TSPResult", "Matrix from file", nullptr));
        radioButton_2->setText(QApplication::translate("TSPResult", "Random generated matrix", nullptr));
        label->setText(QApplication::translate("TSPResult", "Interval points", nullptr));
        label_2->setText(QApplication::translate("TSPResult", "From", nullptr));
        label_3->setText(QApplication::translate("TSPResult", "To", nullptr));
        label_4->setText(QApplication::translate("TSPResult", "Step", nullptr));
        editPointFrom->setText(QApplication::translate("TSPResult", "6", nullptr));
        editPointTo->setText(QApplication::translate("TSPResult", "10", nullptr));
        editPointStep->setText(QApplication::translate("TSPResult", "2", nullptr));
        label_5->setText(QApplication::translate("TSPResult", "Interval length", nullptr));
        label_6->setText(QApplication::translate("TSPResult", "From", nullptr));
        editLengthTo->setText(QApplication::translate("TSPResult", "100", nullptr));
        label_7->setText(QApplication::translate("TSPResult", "To", nullptr));
        editLengthFrom->setText(QApplication::translate("TSPResult", "25", nullptr));
        label_8->setText(QApplication::translate("TSPResult", "Quantity cycles", nullptr));
        editQuantCycle->setText(QApplication::translate("TSPResult", "5", nullptr));
        label_9->setText(QApplication::translate("TSPResult", "MAX quantity points=", nullptr));
        label_10->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class TSPResult: public Ui_TSPResult {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TSPRESULT_H
